#!/usr/bin/env bash

if [ "$1" == "start" ]; then
    docker-compose start
fi

if [ "$1" == "stop" ]; then
    docker-compose stop
fi

if [ "$1" == "update" ]; then    
    docker-compose pull && docker pull php:7.4-fpm-alpine && docker-compose up --build -d && docker image prune -f
fi

if [ "$1" == "setup" ]; then
  echo 'Setting system...' \
  && read -p "Enter your domain (ex:mydomain.com) : " DOMAIN
  read -p "Enter your email address for SSL certificate (ex:myemail@email.com) : " EMAIL
  read -p "Enter your root database password (ex:rootdbpassword) : " ROOTDBPASSWORD
  read -p "Enter your database username for rhymix (ex:dbuser) : " DATABASEUSER
  read -p "Enter your database password for rhymix (ex:dbpassword) : " -i "dbuserpassword" DATABASEPASSWORD
  read -p "Enter your database name for rhymix (ex:rhymix) : " DATABASE \
  && rm -rf rhymix; git clone https://github.com/woosungchoi/docker-rhymix rhymix \
  && cd rhymix \
  && sed -i "s/<rootdbpassword>/$ROOTDBPASSWORD/g" .env \
  && sed -i "s/<databaseuser>/$DATABASEUSER/g" .env \
  && sed -i "s/<databasepassword>/$DATABASEPASSWORD/g" .env \
  && sed -i "s/<database>/$DATABASE/g" .env \
  && sed -i "s/<domain>/$DOMAIN/g" docker-compose.yml \
  && sed -i "s/<domain>/$DOMAIN/g" docker-compose.production.yml \
  && sed -i "s/<email>/$EMAIL/g" docker-compose.yml \
  && sed -i "s/<domain>/$DOMAIN/g" nginx/conf.d/ssl-conf \
  && sed -i "s/<domain>/$DOMAIN/g" nginx/conf.d/rhymix.conf \
  && sed -i "s/<domain>/$DOMAIN/g" nginx/conf.d/portainer.conf \
  && sed -i "s/<domain>/$DOMAIN/g" nginx/conf.d/phpmyadmin.conf \
  && echo 'Setting timezone to Asia/Seoul...' \
  && sudo timedatectl set-timezone Asia/Seoul \
  && echo 'Installing Docker...' \
  && sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y \
  && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - \
  && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" -y \
  && sudo apt update -y \
  && sudo apt install docker-ce docker-ce-cli containerd.io -y \
  && if [ ! -f /usr/local/bin/docker-compose ] ; then
        echo 'Installing Docker Compose...' \
        && sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
        && sudo chmod +x /usr/local/bin/docker-compose
        else echo 'Skip Installing Docker Compose'
     fi
  echo 'Installing SSL...' \
  && sudo docker-compose up \
  && echo 'Preparing docker-compose up' \
  && sudo docker-compose down -v \
  && sudo mkdir -p /usr/share/nginx/html;
  curl -sSLo nginx/conf.d/options-ssl-nginx https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf \
  && curl -sSLo nginx/conf.d/rhymix-rewrite https://raw.githubusercontent.com/rhymix/rhymix/master/common/manual/server_config/rhymix-nginx.conf \
  && sudo chmod a+x build/docker-entrypoint.sh \
  && sudo chmod a+x dc \
  && mv docker-compose.yml docker-compose.ssl.yml \
  && mv docker-compose.production.yml docker-compose.yml \
  && echo 'Configuring cron...' \
  && echo "0 23 * * * docker start certbot && docker restart nginx >> /var/log/docker_cron.log 2>&1" >> mycron \
  && sudo crontab mycron; rm mycron \
  && echo 'Starting Docker ...' \
  && sudo docker-compose up -d  \
  && echo 'Done! 🎉' \
  && echo 'by Rafael Correa Gomes and Woosung Choi' \
  && echo 'Below is a list of containers.'\
  && sudo docker-compose ps \
  && echo 'Access your rhymix: https://'$DOMAIN;
  echo 'Access your phpmyadmin: https://pma.'$DOMAIN;
  echo 'Access your portainer: https://port.'$DOMAIN;
fi
